# release=summerを持つPodだけにアクセスできるService
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  type: NodePort
  selector:
    app: echo
    release: spring
  ports:
    - name: http
      port: 80
